version: '3.8'

services:

  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    ports:
      - 6379:6379

  django:
    container_name: django
    build: 
      context: ./dcelery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dcelery:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - .env
    depends_on:
      - redis
  
  celery:
    container_name: celery
    build: 
      context: ./dcelery
    command: celery -A dcelery worker --loglevel=info
    volumes:
      - ./dcelery:/usr/src/app
    environment:
      - .env
    depends_on:
      - redis

  